"""add battery_hours to laptops

Revision ID: 9a58f1540afd
Revises: f90767c76341
Create Date: 2026-02-05 16:39:13.367984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a58f1540afd'
down_revision: Union[str, Sequence[str], None] = 'f90767c76341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('battery_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laptops', 'battery_hours')
    # ### end Alembic commands ###
